<?php
if(function_exists("register_field_group")){

    register_field_group(array (
        'id' => 'acf_cours',
        'title' => 'Cours',
        'fields' => array (
            array (
                'key' => 'field_5911c0ab92624',
                'label' => 'Titre Cour 1',
                'name' => 'titre_cours_1',
                'type' => 'text',
                'instructions' => 'Titre du cour 1',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5911c09392623',
                'label' => 'Background-titre-img',
                'name' => 'background-titre-img',
                'type' => 'image',
                'instructions' => 'Image derrière le titre de la page',
                'save_format' => 'id',
                'preview_size' => 'full',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5911c17d0f329',
                'label' => 'Cour 1 IMG',
                'name' => 'cour_1_img',
                'type' => 'image',
                'instructions' => 'L\'image background du cour 1',
                'save_format' => 'id',
                'preview_size' => 'full',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5911c0c392625',
                'label' => 'Text 1',
                'name' => 'text_1',
                'type' => 'text',
                'instructions' => 'Texte du cour 1',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5912f869c447d',
                'label' => 'Titre Cour 2',
                'name' => 'titre_cour_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5912f871c447e',
                'label' => 'Texte 2',
                'name' => 'texte_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5912f8b1accd7',
                'label' => 'IMG Cour 2',
                'name' => 'img_cour_2',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_591d4f9b3c4af',
                'label' => 'Titre Cour 3',
                'name' => 'titre_cour_3',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d4fff912a2',
                'label' => 'Text 3',
                'name' => 'text_3',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d4fac3c4b0',
                'label' => 'Cour 3 IMG',
                'name' => 'cour_3_img',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_591d4fc43c4b1',
                'label' => 'Titre Cour 4',
                'name' => 'titre_cour_4',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d4fcd3c4b2',
                'label' => 'Cour 4 IMG',
                'name' => 'cour_4_img',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_591d5006912a3',
                'label' => 'Text 4',
                'name' => 'text_4',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '35',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_index',
        'title' => 'Index',
        'fields' => array (
            array (
                'key' => 'field_591d766fc61a1',
                'label' => 'Slogan_1',
                'name' => 'slogan_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d76a7c61a2',
                'label' => 'Slogan 2',
                'name' => 'slogan_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d76aec61a3',
                'label' => 'Background Image Slogan',
                'name' => 'background_image_slogan',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_591d76dbc61a4',
                'label' => 'Titre_Content',
                'name' => 'titre_content',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d7709c61a5',
                'label' => 'Titre Content 1',
                'name' => 'titre_content_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d771ec61a6',
                'label' => 'Text Content 1',
                'name' => 'text_content_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d772bc61a7',
                'label' => 'IMG Content 1',
                'name' => 'img_content_1',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_591d7736c61a8',
                'label' => 'Titre content 2',
                'name' => 'titre_content_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d773ec61a9',
                'label' => 'Text Content 2',
                'name' => 'text_content_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591d7750c61aa',
                'label' => 'IMG Content 2',
                'name' => 'img_content_2',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '70',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_presentation',
        'title' => 'Présentation',
        'fields' => array (
            array (
                'key' => 'field_59098eef05aa0',
                'label' => 'Image 1',
                'name' => 'image_1',
                'type' => 'image',
                'instructions' => 'Images Droite',
                'save_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'uploadedTo',
            ),
            array (
                'key' => 'field_5909908405aa1',
                'label' => 'Image 2',
                'name' => 'image_2',
                'type' => 'image',
                'instructions' => 'Image à gauche',
                'save_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'uploadedTo',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '9',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_tarif',
        'title' => 'Tarif',
        'fields' => array (
            array (
                'key' => 'field_5913217d2f709',
                'label' => 'image_background_title',
                'name' => 'image_background_title',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_59132527c3200',
                'label' => 'Titre Offre 1',
                'name' => 'titre_offre_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_59132641e9fa1',
                'label' => 'Prix Offre 1',
                'name' => 'prix_offre_1',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_59099e4913e82',
                'label' => 'Img Offre 1',
                'name' => 'img_offre_1',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'medium',
                'library' => 'all',
            ),
            array (
                'key' => 'field_59132544c3201',
                'label' => 'Titre offre 2',
                'name' => 'titre_offre_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5913265ee9fa2',
                'label' => 'Prix Offre 2',
                'name' => 'prix_offre_2',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_59099e6213e83',
                'label' => 'Img Offre 2',
                'name' => 'img_offre_2',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_59132556c3202',
                'label' => 'Titre Offre 3',
                'name' => 'titre_offre_3',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_59132666e9fa3',
                'label' => 'Prix Offre 3',
                'name' => 'prix_offre_3',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_59099e8313e84',
                'label' => 'Img Offre 3',
                'name' => 'img_offre_3',
                'type' => 'image',
                'save_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '28',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
}
?>
